# Generated by Django 6.1 on 2026-08-22 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('administrator', 'Administrator'), ('teacher', 'Teacher')], default='', help_text='Primary role of this user within the school system.', max_length=20),
        ),
    ]
