# Generated by Django 6.1 on 2026-08-22 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, default='', help_text='Primary contact phone number.', max_length=20)),
                ('email', models.EmailField(blank=True, default='', help_text='Contact email address.', max_length=254)),
                ('relationship', models.CharField(blank=True, default='', help_text='Relationship to the student, e.g. "Father", "Mother", "Uncle".', max_length=50)),
                ('address', models.TextField(blank=True, default='', help_text='Physical or mailing address.')),
                ('is_primary_contact', models.BooleanField(default=False, help_text='Whether this guardian is the primary contact for all associated students.')),
                ('user', models.OneToOneField(blank=True, help_text='System account for this guardian, if they have one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardian_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guardian',
                'verbose_name_plural': 'Guardians',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(help_text='School-assigned admission/registration number. Must be unique.', max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, help_text='Student date of birth.', null=True)),
                ('gender', models.CharField(blank=True, default='', help_text='Gender, e.g. "Male", "Female".', max_length=10)),
                ('date_of_admission', models.DateField(help_text='Date the student was first admitted to the school.')),
                ('status', models.CharField(choices=[('active', 'Active'), ('graduated', 'Graduated'), ('transferred', 'Transferred'), ('suspended', 'Suspended'), ('withdrawn', 'Withdrawn')], default='active', help_text='Current lifecycle status of the student.', max_length=15)),
                ('photo', models.ImageField(blank=True, help_text='Student passport photo.', null=True, upload_to='students/photos/')),
                ('user', models.OneToOneField(blank=True, help_text='System account for this student, if one exists.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentGuardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(blank=True, default='', help_text='Relationship of this guardian to this specific student.', max_length=50)),
                ('is_primary', models.BooleanField(default=False, help_text='Whether this guardian is the primary contact for this student.')),
                ('can_pickup', models.BooleanField(default=True, help_text='Whether this guardian is authorised to pick up the student.')),
                ('notes', models.TextField(blank=True, default='', help_text='Any additional notes about this student-guardian relationship.')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_guardians', to='students.guardian')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_guardians', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Guardian',
                'verbose_name_plural': 'Student Guardians',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='guardians',
            field=models.ManyToManyField(blank=True, related_name='students', through='students.StudentGuardian', to='students.guardian'),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_enrolled', models.DateField(help_text='Date this enrollment record was created.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this enrollment is currently active.')),
                ('notes', models.TextField(blank=True, default='', help_text='Optional notes about this enrollment.')),
                ('academic_year', models.ForeignKey(help_text='The academic year of this enrollment.', on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='administration.academicyear')),
                ('school_class', models.ForeignKey(help_text='The class/grade level the student is enrolled in.', on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='administration.class')),
                ('stream', models.ForeignKey(blank=True, help_text='The stream within the class, if applicable.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='administration.stream')),
                ('term', models.ForeignKey(blank=True, help_text='The term of this enrollment. Leave blank if enrollment spans the whole year.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='administration.term')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student')),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'ordering': ['-academic_year__start_date', 'student'],
                'constraints': [models.UniqueConstraint(fields=('student', 'academic_year', 'term', 'school_class', 'stream'), name='unique_enrollment_per_student_year_term_class_stream')],
            },
        ),
        migrations.AddConstraint(
            model_name='studentguardian',
            constraint=models.UniqueConstraint(fields=('student', 'guardian'), name='unique_student_guardian'),
        ),
    ]
