# Generated by Django 6.1 on 2026-08-26 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(help_text='School-assigned admission/registration number. Must be unique.', max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, help_text='Student date of birth.', null=True)),
                ('gender', models.CharField(blank=True, default='', help_text='Gender, e.g. "Male", "Female".', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('graduated', 'Graduated'), ('transferred', 'Transferred'), ('suspended', 'Suspended'), ('withdrawn', 'Withdrawn')], default='active', help_text='Current lifecycle status of the student.', max_length=15)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(help_text='Date this enrollment record was created.')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('withdrawn', 'Withdrawn'), ('transferred', 'Transferred')], default='active', help_text='Current status of this enrollment.', max_length=15)),
                ('academic_year', models.ForeignKey(help_text='The academic year of this enrollment.', on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='administration.academicyear')),
                ('school_class', models.ForeignKey(help_text='The class/grade level the student is enrolled in.', on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='administration.class')),
                ('stream', models.ForeignKey(blank=True, help_text='The stream within the class, if applicable.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='administration.stream')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student')),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'ordering': ['-academic_year__start_date', 'student'],
                'constraints': [models.UniqueConstraint(fields=('student', 'academic_year', 'school_class', 'stream'), name='unique_enrollment_per_student_year_class_stream')],
            },
        ),
    ]
