# Generated by Django 6.1 on 2026-08-22 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable label, e.g. "2025/2026".', max_length=20, unique=True)),
                ('start_date', models.DateField(help_text='First day of the academic year.')),
                ('end_date', models.DateField(help_text='Last day of the academic year.')),
                ('is_current', models.BooleanField(default=False, help_text='Marks the active academic year. Only one year should be current at a time.')),
            ],
            options={
                'verbose_name': 'Academic Year',
                'verbose_name_plural': 'Academic Years',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Class/grade label, e.g. "Form 1", "Grade 8".', max_length=50, unique=True)),
                ('level', models.PositiveSmallIntegerField(help_text='Numeric level to support ordering (1 = lowest, higher = more advanced).')),
                ('description', models.TextField(blank=True, default='', help_text='Optional notes about this class level.')),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Room identifier, e.g. "Room 101", "Lab A".', max_length=50, unique=True)),
                ('capacity', models.PositiveSmallIntegerField(blank=True, help_text='Maximum number of students the room can hold. Leave blank if unknown.', null=True)),
                ('description', models.TextField(blank=True, default='', help_text='Optional notes, e.g. "Science lab, has fume hood".')),
            ],
            options={
                'verbose_name': 'Classroom',
                'verbose_name_plural': 'Classrooms',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Department name, e.g. "Mathematics", "Sciences".', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description of the department.')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Stream label, e.g. "East", "West", "A", "B".', max_length=50)),
            ],
            options={
                'verbose_name': 'Stream',
                'verbose_name_plural': 'Streams',
                'ordering': ['school_class', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Term label, e.g. "Term 1".', max_length=50)),
                ('term_number', models.PositiveSmallIntegerField(help_text='Ordinal position within the academic year (1, 2, 3, …).')),
                ('start_date', models.DateField(help_text='First day of the term.')),
                ('end_date', models.DateField(help_text='Last day of the term.')),
                ('is_current', models.BooleanField(default=False, help_text='Marks the active term.')),
            ],
            options={
                'verbose_name': 'Term',
                'verbose_name_plural': 'Terms',
                'ordering': ['academic_year', 'term_number'],
            },
        ),
    ]
