# Generated by Django 6.1 on 2026-08-26 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable label, e.g. "2025/2026".', max_length=20, unique=True)),
                ('start_date', models.DateField(help_text='First day of the academic year.')),
                ('end_date', models.DateField(help_text='Last day of the academic year.')),
                ('is_current', models.BooleanField(default=False, help_text='Marks the active academic year. Only one year should be current at a time.')),
            ],
            options={
                'verbose_name': 'Academic Year',
                'verbose_name_plural': 'Academic Years',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Class/grade label, e.g. "Form 1", "Grade 8".', max_length=50, unique=True)),
                ('level', models.PositiveSmallIntegerField(help_text='Numeric level to support ordering (1 = lowest, higher = more advanced).')),
                ('capacity', models.PositiveSmallIntegerField(blank=True, help_text='Maximum number of students this class can hold. Leave blank if unknown.', null=True)),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Stream label, e.g. "East", "West", "A", "B".', max_length=50)),
                ('school_class', models.ForeignKey(help_text='The class level this stream belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='administration.class')),
            ],
            options={
                'verbose_name': 'Stream',
                'verbose_name_plural': 'Streams',
                'ordering': ['school_class', 'name'],
                'constraints': [models.UniqueConstraint(fields=('school_class', 'name'), name='unique_stream_name_per_class')],
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Term label, e.g. "Term 1".', max_length=50)),
                ('term_number', models.PositiveSmallIntegerField(help_text='Ordinal position within the academic year (1, 2, 3, …).')),
                ('start_date', models.DateField(help_text='First day of the term.')),
                ('end_date', models.DateField(help_text='Last day of the term.')),
                ('academic_year', models.ForeignKey(help_text='The academic year this term belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='administration.academicyear')),
            ],
            options={
                'verbose_name': 'Term',
                'verbose_name_plural': 'Terms',
                'ordering': ['academic_year', 'term_number'],
                'constraints': [models.UniqueConstraint(fields=('academic_year', 'term_number'), name='unique_term_number_per_year')],
            },
        ),
    ]
