# Generated by Django 6.1 on 2026-08-22 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        ('teaching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, help_text='The teacher currently heading this department. Optional.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='teaching.teacher'),
        ),
        migrations.AddField(
            model_name='stream',
            name='school_class',
            field=models.ForeignKey(help_text='The class level this stream belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='administration.class'),
        ),
        migrations.AddField(
            model_name='term',
            name='academic_year',
            field=models.ForeignKey(help_text='The academic year this term belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='administration.academicyear'),
        ),
        migrations.AddConstraint(
            model_name='stream',
            constraint=models.UniqueConstraint(fields=('school_class', 'name'), name='unique_stream_name_per_class'),
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.UniqueConstraint(fields=('academic_year', 'term_number'), name='unique_term_number_per_year'),
        ),
    ]
