# Generated by Django 6.1 on 2026-08-22 02:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short heading for the announcement.', max_length=255)),
                ('body', models.TextField(help_text='Full announcement text.')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this announcement was published.')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiry date/time after which the announcement is no longer active.', null=True)),
                ('is_published', models.BooleanField(default=True, help_text='Whether this announcement is visible to its audience.')),
                ('target_roles', models.JSONField(blank=True, default=list, help_text='List of role strings that should see this announcement, e.g. ["teacher", "parent"]. Empty list means all roles.')),
                ('author', models.ForeignKey(blank=True, help_text='The user who created this announcement.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, default='', help_text='Optional message subject.', max_length=255)),
                ('body', models.TextField(help_text='Message body.')),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this message was sent.')),
                ('is_read', models.BooleanField(default=False, help_text='Whether the recipient has read this message.')),
                ('read_at', models.DateTimeField(blank=True, help_text='When the recipient read this message.', null=True)),
                ('recipient', models.ForeignKey(help_text='The user this message was sent to.', on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(help_text='The user who sent this message.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short heading for the notification.', max_length=255)),
                ('body', models.TextField(blank=True, default='', help_text='Optional longer notification body.')),
                ('is_read', models.BooleanField(default=False, help_text='Whether the recipient has read this notification.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this notification was created.')),
                ('read_at', models.DateTimeField(blank=True, help_text='When the recipient marked this notification as read.', null=True)),
                ('recipient', models.ForeignKey(help_text='The user this notification is addressed to.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
