# Generated by Django 6.1 on 2026-08-22 02:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('teaching', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], help_text='Attendance status for this student in this session.', max_length=10)),
                ('remarks', models.TextField(blank=True, default='', help_text='Optional remarks, e.g. reason for lateness or excuse details.')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when this record was first created.')),
                ('student', models.ForeignKey(help_text='The student this record is for.', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.student')),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['session', 'student'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], help_text='The attendance status before the correction.', max_length=10)),
                ('new_status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], help_text='The attendance status after the correction.', max_length=10)),
                ('reason', models.TextField(help_text='Mandatory reason/justification for this correction.')),
                ('corrected_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when this correction was made.')),
                ('corrected_by', models.ForeignKey(help_text='The authorised user who made this correction.', on_delete=django.db.models.deletion.PROTECT, related_name='attendance_corrections', to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(help_text='The attendance record that was corrected.', on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='attendance.attendancerecord')),
            ],
            options={
                'verbose_name': 'Attendance Correction',
                'verbose_name_plural': 'Attendance Corrections',
                'ordering': ['-corrected_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Calendar date on which this attendance session occurred.')),
                ('taken_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when attendance was first recorded.')),
                ('notes', models.TextField(blank=True, default='', help_text='Optional session-level notes.')),
                ('lesson', models.ForeignKey(help_text='The scheduled lesson this attendance session corresponds to.', on_delete=django.db.models.deletion.PROTECT, related_name='attendance_sessions', to='teaching.lesson')),
                ('taken_by', models.ForeignKey(help_text='The user who recorded this attendance session.', on_delete=django.db.models.deletion.PROTECT, related_name='attendance_sessions_taken', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendance Session',
                'verbose_name_plural': 'Attendance Sessions',
                'ordering': ['-date', 'lesson'],
            },
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='session',
            field=models.ForeignKey(help_text='The attendance session this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='records', to='attendance.attendancesession'),
        ),
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.UniqueConstraint(fields=('lesson', 'date'), name='unique_attendance_session_per_lesson_date'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('session', 'student'), name='unique_attendance_record_per_session_student'),
        ),
    ]
