# Generated by Django 6.1 on 2026-08-26 19:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        ('students', '0001_initial'),
        ('teaching', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Calendar date on which this attendance session occurred.')),
                ('session_type', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('full_day', 'Full Day')], default='morning', help_text='Type of attendance session.', max_length=15)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when this session record was created.')),
                ('academic_year', models.ForeignKey(help_text='The academic year this session belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='attendance_sessions', to='administration.academicyear')),
                ('school_class', models.ForeignKey(help_text='The class this attendance session is for.', on_delete=django.db.models.deletion.PROTECT, related_name='attendance_sessions', to='administration.class')),
                ('stream', models.ForeignKey(blank=True, help_text='The stream within the class, if applicable.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_sessions', to='administration.stream')),
                ('teacher', models.ForeignKey(help_text='The teacher who conducted this attendance session.', on_delete=django.db.models.deletion.PROTECT, related_name='attendance_sessions', to='teaching.teacher')),
            ],
            options={
                'verbose_name': 'Attendance Session',
                'verbose_name_plural': 'Attendance Sessions',
                'ordering': ['-date', 'school_class', 'stream'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], help_text='Attendance status for this student in this session.', max_length=10)),
                ('remarks', models.TextField(blank=True, default='', help_text='Optional remarks, e.g. reason for lateness or excuse details.')),
                ('student', models.ForeignKey(help_text='The student this record is for.', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.student')),
                ('session', models.ForeignKey(help_text='The attendance session this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='records', to='attendance.attendancesession')),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['session', 'student'],
            },
        ),
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.UniqueConstraint(fields=('school_class', 'stream', 'date', 'session_type'), name='unique_attendance_session_per_class_stream_date_type'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('session', 'student'), name='unique_attendance_record_per_session_student'),
        ),
    ]
