# Generated by Django 6.1 on 2026-08-22 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Subject name, e.g. "Mathematics", "English Language".', max_length=100, unique=True)),
                ('code', models.CharField(help_text='Short subject code, e.g. "MATH", "ENG".', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this subject is currently offered.')),
                ('department', models.ForeignKey(blank=True, help_text='Department responsible for this subject.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='administration.department')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(help_text='School-assigned employee/staff number.', max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', help_text='Work email address.', max_length=254)),
                ('date_joined', models.DateField(blank=True, help_text='Date the teacher joined the school.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this teacher is currently active at the school.')),
                ('department', models.ForeignKey(blank=True, help_text='Department this teacher belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='administration.department')),
                ('user', models.OneToOneField(blank=True, help_text='System account for this teacher, if one exists.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this assignment is currently in effect.')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_assignments', to='administration.academicyear')),
                ('school_class', models.ForeignKey(help_text='The class level this assignment covers.', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='administration.class')),
                ('stream', models.ForeignKey(blank=True, help_text='The specific stream, if the assignment is stream-specific.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='administration.stream')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='teaching.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='teaching.teacher')),
            ],
            options={
                'verbose_name': 'Teacher Assignment',
                'verbose_name_plural': 'Teacher Assignments',
                'ordering': ['academic_year', 'teacher', 'subject'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], help_text='Day of the week this lesson occurs.')),
                ('start_time', models.TimeField(help_text='Scheduled start time.')),
                ('end_time', models.TimeField(help_text='Scheduled end time.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this lesson is currently scheduled.')),
                ('classroom', models.ForeignKey(blank=True, help_text='The physical room where this lesson takes place.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='administration.classroom')),
                ('term', models.ForeignKey(help_text='The term in which this lesson is scheduled.', on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='administration.term')),
                ('assignment', models.ForeignKey(help_text='The teacher-subject-class assignment this lesson belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='teaching.teacherassignment')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
                'ordering': ['term', 'day_of_week', 'start_time'],
            },
        ),
        migrations.AddConstraint(
            model_name='teacherassignment',
            constraint=models.UniqueConstraint(fields=('teacher', 'subject', 'school_class', 'stream', 'academic_year'), name='unique_teacher_assignment'),
        ),
    ]
