# Generated by Django 6.1 on 2026-08-26 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Subject name, e.g. "Mathematics", "English Language".', max_length=100, unique=True)),
                ('code', models.CharField(help_text='Short subject code, e.g. "MATH", "ENG".', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(help_text='School-assigned employee/staff number.', max_length=30, unique=True)),
                ('qualification', models.CharField(blank=True, default='', help_text='Academic or professional qualification, e.g. "B.Ed Mathematics".', max_length=200)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('user', models.OneToOneField(blank=True, help_text='System account for this teacher.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'ordering': ['employee_number'],
            },
        ),
        migrations.CreateModel(
            name='ClassParentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this Class Parent assignment is currently active.')),
                ('academic_year', models.ForeignKey(help_text='The academic year for which this assignment is valid.', on_delete=django.db.models.deletion.PROTECT, related_name='class_parent_assignments', to='administration.academicyear')),
                ('school_class', models.ForeignKey(help_text='The class for which this teacher is Class Parent.', on_delete=django.db.models.deletion.CASCADE, related_name='class_parent_assignments', to='administration.class')),
                ('stream', models.ForeignKey(blank=True, help_text='The specific stream within the class, if applicable. Leave blank if the teacher is Class Parent for the whole class.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_parent_assignments', to='administration.stream')),
                ('teacher', models.ForeignKey(help_text='The teacher assigned Class Parent responsibility.', on_delete=django.db.models.deletion.CASCADE, related_name='class_parent_assignments', to='teaching.teacher')),
            ],
            options={
                'verbose_name': 'Class Parent Assignment',
                'verbose_name_plural': 'Class Parent Assignments',
                'ordering': ['academic_year', 'school_class', 'stream'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('school_class', 'stream', 'academic_year'), name='unique_active_class_parent_per_class_stream_year')],
            },
        ),
        migrations.CreateModel(
            name='TeachingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teaching_assignments', to='administration.academicyear')),
                ('school_class', models.ForeignKey(help_text='The class level this assignment covers.', on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='administration.class')),
                ('stream', models.ForeignKey(blank=True, help_text='The specific stream, if the assignment is stream-specific.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='administration.stream')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='teaching.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='teaching.teacher')),
            ],
            options={
                'verbose_name': 'Teaching Assignment',
                'verbose_name_plural': 'Teaching Assignments',
                'ordering': ['academic_year', 'teacher', 'subject'],
                'constraints': [models.UniqueConstraint(fields=('teacher', 'subject', 'school_class', 'stream', 'academic_year'), name='unique_teaching_assignment')],
            },
        ),
    ]
