# Generated by Django 6.1 on 2026-08-22 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_initial'),
        ('teaching', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassParentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this Class Parent assignment is currently active.')),
                ('notes', models.TextField(blank=True, default='', help_text='Optional notes about this assignment.')),
                ('academic_year', models.ForeignKey(help_text='The academic year for which this assignment is valid.', on_delete=django.db.models.deletion.PROTECT, related_name='class_parent_assignments', to='administration.academicyear')),
                ('school_class', models.ForeignKey(help_text='The class for which this teacher is Class Parent.', on_delete=django.db.models.deletion.CASCADE, related_name='class_parent_assignments', to='administration.class')),
                ('stream', models.ForeignKey(blank=True, help_text='The specific stream within the class, if applicable. Leave blank if the teacher is Class Parent for the whole class.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_parent_assignments', to='administration.stream')),
                ('teacher', models.ForeignKey(help_text='The teacher assigned Class Parent responsibility.', on_delete=django.db.models.deletion.CASCADE, related_name='class_parent_assignments', to='teaching.teacher')),
            ],
            options={
                'verbose_name': 'Class Parent Assignment',
                'verbose_name_plural': 'Class Parent Assignments',
                'ordering': ['academic_year', 'school_class', 'stream'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('school_class', 'stream', 'academic_year'), name='unique_active_class_parent_per_class_stream_year')],
            },
        ),
    ]
